#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



public partial class DocSamples : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public DocSamples(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DocSamples(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DocSamples(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DocSamples(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<BikeShop> BikeShop
	{
		get
		{
			return this.GetTable<BikeShop>();
		}
	}
	
	public System.Data.Linq.Table<BirthVariation> BirthVariation
	{
		get
		{
			return this.GetTable<BirthVariation>();
		}
	}
	
	public System.Data.Linq.Table<BrowserUsage> BrowserUsage
	{
		get
		{
			return this.GetTable<BrowserUsage>();
		}
	}
	
	public System.Data.Linq.Table<CarProduction> CarProduction
	{
		get
		{
			return this.GetTable<CarProduction>();
		}
	}
	
	public System.Data.Linq.Table<CompanyDataBubble> CompanyDataBubble
	{
		get
		{
			return this.GetTable<CompanyDataBubble>();
		}
	}
	
	public System.Data.Linq.Table<Countries> Countries
	{
		get
		{
			return this.GetTable<Countries>();
		}
	}
	
	public System.Data.Linq.Table<DDOSAttack> DDOSAttack
	{
		get
		{
			return this.GetTable<DDOSAttack>();
		}
	}
	
	public System.Data.Linq.Table<FinancialData> FinancialData
	{
		get
		{
			return this.GetTable<FinancialData>();
		}
	}
	
	public System.Data.Linq.Table<GasMeasurements> GasMeasurements
	{
		get
		{
			return this.GetTable<GasMeasurements>();
		}
	}
	
	public System.Data.Linq.Table<MiamiClimate> MiamiClimate
	{
		get
		{
			return this.GetTable<MiamiClimate>();
		}
	}
	
	public System.Data.Linq.Table<NewConstructions> NewConstructions
	{
		get
		{
			return this.GetTable<NewConstructions>();
		}
	}
	
	public System.Data.Linq.Table<OilPriceandEuroRate> OilPriceandEuroRate
	{
		get
		{
			return this.GetTable<OilPriceandEuroRate>();
		}
	}
	
	public System.Data.Linq.Table<OldFinancialData> OldFinancialData
	{
		get
		{
			return this.GetTable<OldFinancialData>();
		}
	}
	
	public System.Data.Linq.Table<PatientSamples> PatientSamples
	{
		get
		{
			return this.GetTable<PatientSamples>();
		}
	}
	
	public System.Data.Linq.Table<PopulationData> PopulationData
	{
		get
		{
			return this.GetTable<PopulationData>();
		}
	}
	
	public System.Data.Linq.Table<ProductSales> ProductSales
	{
		get
		{
			return this.GetTable<ProductSales>();
		}
	}
	
	public System.Data.Linq.Table<RealEstateAgents> RealEstateAgents
	{
		get
		{
			return this.GetTable<RealEstateAgents>();
		}
	}
	
	public System.Data.Linq.Table<RealEstateData> RealEstateData
	{
		get
		{
			return this.GetTable<RealEstateData>();
		}
	}
	
	public System.Data.Linq.Table<RealEstateSales> RealEstateSales
	{
		get
		{
			return this.GetTable<RealEstateSales>();
		}
	}
	
	public System.Data.Linq.Table<SouthAmericaPopulation> SouthAmericaPopulation
	{
		get
		{
			return this.GetTable<SouthAmericaPopulation>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class BikeShop
{
	
	private string _SubjectIdName;
	
	private System.Nullable<System.DateTime> _DateDelivered;
	
	private System.Nullable<decimal> _Price;
	
	private string _ShipToState_Province;
	
	public BikeShop()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectIdName", DbType="NVarChar(50)")]
	public string SubjectIdName
	{
		get
		{
			return this._SubjectIdName;
		}
		set
		{
			if ((this._SubjectIdName != value))
			{
				this._SubjectIdName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateDelivered", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateDelivered
	{
		get
		{
			return this._DateDelivered;
		}
		set
		{
			if ((this._DateDelivered != value))
			{
				this._DateDelivered = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> Price
	{
		get
		{
			return this._Price;
		}
		set
		{
			if ((this._Price != value))
			{
				this._Price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipToState_Province", DbType="NVarChar(50)")]
	public string ShipToState_Province
	{
		get
		{
			return this._ShipToState_Province;
		}
		set
		{
			if ((this._ShipToState_Province != value))
			{
				this._ShipToState_Province = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class BirthVariation
{
	
	private int _Id;
	
	private string _Year;
	
	private double _Male;
	
	private double _Female;
	
	public BirthVariation()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this._Id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NChar(4) NOT NULL", CanBeNull=false)]
	public string Year
	{
		get
		{
			return this._Year;
		}
		set
		{
			if ((this._Year != value))
			{
				this._Year = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Male", DbType="Float NOT NULL")]
	public double Male
	{
		get
		{
			return this._Male;
		}
		set
		{
			if ((this._Male != value))
			{
				this._Male = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Female", DbType="Float NOT NULL")]
	public double Female
	{
		get
		{
			return this._Female;
		}
		set
		{
			if ((this._Female != value))
			{
				this._Female = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class BrowserUsage
{
	
	private System.Nullable<double> _Id;
	
	private string _Browser;
	
	private string _Region;
	
	private System.Nullable<System.DateTime> _UsageDate;
	
	private System.Nullable<double> _Usage;
	
	public BrowserUsage()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Float")]
	public System.Nullable<double> Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this._Id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Browser", DbType="NVarChar(255)")]
	public string Browser
	{
		get
		{
			return this._Browser;
		}
		set
		{
			if ((this._Browser != value))
			{
				this._Browser = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="NVarChar(255)")]
	public string Region
	{
		get
		{
			return this._Region;
		}
		set
		{
			if ((this._Region != value))
			{
				this._Region = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsageDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> UsageDate
	{
		get
		{
			return this._UsageDate;
		}
		set
		{
			if ((this._UsageDate != value))
			{
				this._UsageDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usage", DbType="Float")]
	public System.Nullable<double> Usage
	{
		get
		{
			return this._Usage;
		}
		set
		{
			if ((this._Usage != value))
			{
				this._Usage = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class CarProduction
{
	
	private int _Id;
	
	private int _Sedan;
	
	private int _Coupe;
	
	private int _SUV;
	
	private string _Month;
	
	public CarProduction()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this._Id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sedan", DbType="Int NOT NULL")]
	public int Sedan
	{
		get
		{
			return this._Sedan;
		}
		set
		{
			if ((this._Sedan != value))
			{
				this._Sedan = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coupe", DbType="Int NOT NULL")]
	public int Coupe
	{
		get
		{
			return this._Coupe;
		}
		set
		{
			if ((this._Coupe != value))
			{
				this._Coupe = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUV", DbType="Int NOT NULL")]
	public int SUV
	{
		get
		{
			return this._SUV;
		}
		set
		{
			if ((this._SUV != value))
			{
				this._SUV = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="NChar(3) NOT NULL", CanBeNull=false)]
	public string Month
	{
		get
		{
			return this._Month;
		}
		set
		{
			if ((this._Month != value))
			{
				this._Month = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class CompanyDataBubble
{
	
	private string _Symbol;
	
	private System.Nullable<double> _Strength;
	
	private System.Nullable<double> _Rank;
	
	private System.Nullable<double> _PE;
	
	public CompanyDataBubble()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Symbol", DbType="NVarChar(255)")]
	public string Symbol
	{
		get
		{
			return this._Symbol;
		}
		set
		{
			if ((this._Symbol != value))
			{
				this._Symbol = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Strength", DbType="Float")]
	public System.Nullable<double> Strength
	{
		get
		{
			return this._Strength;
		}
		set
		{
			if ((this._Strength != value))
			{
				this._Strength = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="Float")]
	public System.Nullable<double> Rank
	{
		get
		{
			return this._Rank;
		}
		set
		{
			if ((this._Rank != value))
			{
				this._Rank = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PE", DbType="Float")]
	public System.Nullable<double> PE
	{
		get
		{
			return this._PE;
		}
		set
		{
			if ((this._PE != value))
			{
				this._PE = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class Countries
{
	
	private string _Country;
	
	private System.Nullable<double> _LEI;
	
	private System.Nullable<double> _GDPPC;
	
	public Countries()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(255)")]
	public string Country
	{
		get
		{
			return this._Country;
		}
		set
		{
			if ((this._Country != value))
			{
				this._Country = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LEI", DbType="Float")]
	public System.Nullable<double> LEI
	{
		get
		{
			return this._LEI;
		}
		set
		{
			if ((this._LEI != value))
			{
				this._LEI = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GDPPC", DbType="Float")]
	public System.Nullable<double> GDPPC
	{
		get
		{
			return this._GDPPC;
		}
		set
		{
			if ((this._GDPPC != value))
			{
				this._GDPPC = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class DDOSAttack
{
	
	private System.Nullable<System.DateTime> _EventTime;
	
	private System.Nullable<double> _HitsHour;
	
	private System.Nullable<double> _HitsSec;
	
	private System.Nullable<double> _Hosts;
	
	private System.Nullable<double> _NewHosts;
	
	public DDOSAttack()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> EventTime
	{
		get
		{
			return this._EventTime;
		}
		set
		{
			if ((this._EventTime != value))
			{
				this._EventTime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HitsHour", DbType="Float")]
	public System.Nullable<double> HitsHour
	{
		get
		{
			return this._HitsHour;
		}
		set
		{
			if ((this._HitsHour != value))
			{
				this._HitsHour = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HitsSec", DbType="Float")]
	public System.Nullable<double> HitsSec
	{
		get
		{
			return this._HitsSec;
		}
		set
		{
			if ((this._HitsSec != value))
			{
				this._HitsSec = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hosts", DbType="Float")]
	public System.Nullable<double> Hosts
	{
		get
		{
			return this._Hosts;
		}
		set
		{
			if ((this._Hosts != value))
			{
				this._Hosts = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewHosts", DbType="Float")]
	public System.Nullable<double> NewHosts
	{
		get
		{
			return this._NewHosts;
		}
		set
		{
			if ((this._NewHosts != value))
			{
				this._NewHosts = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class FinancialData
{
	
	private System.Nullable<System.DateTime> _TransDate;
	
	private System.Nullable<double> _Open;
	
	private System.Nullable<double> _High;
	
	private System.Nullable<double> _Low;
	
	private System.Nullable<double> _Close;
	
	private System.Nullable<double> _Volume;
	
	public FinancialData()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> TransDate
	{
		get
		{
			return this._TransDate;
		}
		set
		{
			if ((this._TransDate != value))
			{
				this._TransDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Open", DbType="Float")]
	public System.Nullable<double> Open
	{
		get
		{
			return this._Open;
		}
		set
		{
			if ((this._Open != value))
			{
				this._Open = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Float")]
	public System.Nullable<double> High
	{
		get
		{
			return this._High;
		}
		set
		{
			if ((this._High != value))
			{
				this._High = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Low", DbType="Float")]
	public System.Nullable<double> Low
	{
		get
		{
			return this._Low;
		}
		set
		{
			if ((this._Low != value))
			{
				this._Low = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Close", DbType="Float")]
	public System.Nullable<double> Close
	{
		get
		{
			return this._Close;
		}
		set
		{
			if ((this._Close != value))
			{
				this._Close = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Float")]
	public System.Nullable<double> Volume
	{
		get
		{
			return this._Volume;
		}
		set
		{
			if ((this._Volume != value))
			{
				this._Volume = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class GasMeasurements
{
	
	private System.Nullable<double> _K;
	
	private System.Nullable<double> _C;
	
	private System.Nullable<double> _F;
	
	private System.Nullable<double> _KPa;
	
	private System.Nullable<double> _Atm;
	
	private System.Nullable<double> _Psi;
	
	private System.Nullable<double> _Torr;
	
	public GasMeasurements()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_K", DbType="Float")]
	public System.Nullable<double> K
	{
		get
		{
			return this._K;
		}
		set
		{
			if ((this._K != value))
			{
				this._K = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C", DbType="Float")]
	public System.Nullable<double> C
	{
		get
		{
			return this._C;
		}
		set
		{
			if ((this._C != value))
			{
				this._C = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F", DbType="Float")]
	public System.Nullable<double> F
	{
		get
		{
			return this._F;
		}
		set
		{
			if ((this._F != value))
			{
				this._F = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="kPa", Storage="_KPa", DbType="Float")]
	public System.Nullable<double> KPa
	{
		get
		{
			return this._KPa;
		}
		set
		{
			if ((this._KPa != value))
			{
				this._KPa = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="atm", Storage="_Atm", DbType="Float")]
	public System.Nullable<double> Atm
	{
		get
		{
			return this._Atm;
		}
		set
		{
			if ((this._Atm != value))
			{
				this._Atm = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="psi", Storage="_Psi", DbType="Float")]
	public System.Nullable<double> Psi
	{
		get
		{
			return this._Psi;
		}
		set
		{
			if ((this._Psi != value))
			{
				this._Psi = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Torr", DbType="Float")]
	public System.Nullable<double> Torr
	{
		get
		{
			return this._Torr;
		}
		set
		{
			if ((this._Torr != value))
			{
				this._Torr = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class MiamiClimate
{
	
	private string _Month;
	
	private System.Nullable<double> _Low;
	
	private System.Nullable<double> _High;
	
	private System.Nullable<double> _Average;
	
	private System.Nullable<double> _Precipitation;
	
	private System.Nullable<double> _WindSpeed;
	
	private System.Nullable<double> _RelativeHumidity;
	
	public MiamiClimate()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="NVarChar(255)")]
	public string Month
	{
		get
		{
			return this._Month;
		}
		set
		{
			if ((this._Month != value))
			{
				this._Month = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Low", DbType="Float")]
	public System.Nullable<double> Low
	{
		get
		{
			return this._Low;
		}
		set
		{
			if ((this._Low != value))
			{
				this._Low = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Float")]
	public System.Nullable<double> High
	{
		get
		{
			return this._High;
		}
		set
		{
			if ((this._High != value))
			{
				this._High = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Average", DbType="Float")]
	public System.Nullable<double> Average
	{
		get
		{
			return this._Average;
		}
		set
		{
			if ((this._Average != value))
			{
				this._Average = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precipitation", DbType="Float")]
	public System.Nullable<double> Precipitation
	{
		get
		{
			return this._Precipitation;
		}
		set
		{
			if ((this._Precipitation != value))
			{
				this._Precipitation = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WindSpeed", DbType="Float")]
	public System.Nullable<double> WindSpeed
	{
		get
		{
			return this._WindSpeed;
		}
		set
		{
			if ((this._WindSpeed != value))
			{
				this._WindSpeed = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelativeHumidity", DbType="Float")]
	public System.Nullable<double> RelativeHumidity
	{
		get
		{
			return this._RelativeHumidity;
		}
		set
		{
			if ((this._RelativeHumidity != value))
			{
				this._RelativeHumidity = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class NewConstructions
{
	
	private System.Nullable<double> _Id;
	
	private System.Nullable<System.DateTime> _Date;
	
	private System.Nullable<double> _Northeast;
	
	private System.Nullable<double> _Midwest;
	
	private System.Nullable<double> _South;
	
	private System.Nullable<double> _West;
	
	public NewConstructions()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Float")]
	public System.Nullable<double> Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this._Id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this._Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Northeast", DbType="Float")]
	public System.Nullable<double> Northeast
	{
		get
		{
			return this._Northeast;
		}
		set
		{
			if ((this._Northeast != value))
			{
				this._Northeast = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Midwest", DbType="Float")]
	public System.Nullable<double> Midwest
	{
		get
		{
			return this._Midwest;
		}
		set
		{
			if ((this._Midwest != value))
			{
				this._Midwest = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_South", DbType="Float")]
	public System.Nullable<double> South
	{
		get
		{
			return this._South;
		}
		set
		{
			if ((this._South != value))
			{
				this._South = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_West", DbType="Float")]
	public System.Nullable<double> West
	{
		get
		{
			return this._West;
		}
		set
		{
			if ((this._West != value))
			{
				this._West = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class OilPriceandEuroRate
{
	
	private System.Nullable<System.DateTime> _TransDate;
	
	private System.Nullable<double> _Price;
	
	private System.Nullable<double> _Euro;
	
	public OilPriceandEuroRate()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> TransDate
	{
		get
		{
			return this._TransDate;
		}
		set
		{
			if ((this._TransDate != value))
			{
				this._TransDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float")]
	public System.Nullable<double> Price
	{
		get
		{
			return this._Price;
		}
		set
		{
			if ((this._Price != value))
			{
				this._Price = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Euro", DbType="Float")]
	public System.Nullable<double> Euro
	{
		get
		{
			return this._Euro;
		}
		set
		{
			if ((this._Euro != value))
			{
				this._Euro = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class OldFinancialData
{
	
	private System.Nullable<System.DateTime> _TransDate;
	
	private System.Nullable<double> _Open;
	
	private System.Nullable<double> _High;
	
	private System.Nullable<double> _Low;
	
	private System.Nullable<double> _Close;
	
	public OldFinancialData()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> TransDate
	{
		get
		{
			return this._TransDate;
		}
		set
		{
			if ((this._TransDate != value))
			{
				this._TransDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Open", DbType="Float")]
	public System.Nullable<double> Open
	{
		get
		{
			return this._Open;
		}
		set
		{
			if ((this._Open != value))
			{
				this._Open = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Float")]
	public System.Nullable<double> High
	{
		get
		{
			return this._High;
		}
		set
		{
			if ((this._High != value))
			{
				this._High = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Low", DbType="Float")]
	public System.Nullable<double> Low
	{
		get
		{
			return this._Low;
		}
		set
		{
			if ((this._Low != value))
			{
				this._Low = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Close", DbType="Float")]
	public System.Nullable<double> Close
	{
		get
		{
			return this._Close;
		}
		set
		{
			if ((this._Close != value))
			{
				this._Close = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class PatientSamples
{
	
	private System.Nullable<double> _Height;
	
	private System.Nullable<double> _Weight;
	
	public PatientSamples()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="Float")]
	public System.Nullable<double> Height
	{
		get
		{
			return this._Height;
		}
		set
		{
			if ((this._Height != value))
			{
				this._Height = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Float")]
	public System.Nullable<double> Weight
	{
		get
		{
			return this._Weight;
		}
		set
		{
			if ((this._Weight != value))
			{
				this._Weight = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class PopulationData
{
	
	private string _Range;
	
	private System.Nullable<double> _Male;
	
	private System.Nullable<double> _Female;
	
	public PopulationData()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Range", DbType="NVarChar(255)")]
	public string Range
	{
		get
		{
			return this._Range;
		}
		set
		{
			if ((this._Range != value))
			{
				this._Range = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Male", DbType="Float")]
	public System.Nullable<double> Male
	{
		get
		{
			return this._Male;
		}
		set
		{
			if ((this._Male != value))
			{
				this._Male = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Female", DbType="Float")]
	public System.Nullable<double> Female
	{
		get
		{
			return this._Female;
		}
		set
		{
			if ((this._Female != value))
			{
				this._Female = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class ProductSales
{
	
	private string _Month;
	
	private System.Nullable<decimal> _White;
	
	private System.Nullable<decimal> _Red;
	
	private System.Nullable<decimal> _Sparkling;
	
	public ProductSales()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="NVarChar(50)")]
	public string Month
	{
		get
		{
			return this._Month;
		}
		set
		{
			if ((this._Month != value))
			{
				this._Month = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_White", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> White
	{
		get
		{
			return this._White;
		}
		set
		{
			if ((this._White != value))
			{
				this._White = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Red", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Red
	{
		get
		{
			return this._Red;
		}
		set
		{
			if ((this._Red != value))
			{
				this._Red = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sparkling", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> Sparkling
	{
		get
		{
			return this._Sparkling;
		}
		set
		{
			if ((this._Sparkling != value))
			{
				this._Sparkling = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class RealEstateAgents
{
	
	private int _Agent_id;
	
	private System.Nullable<int> _Brokerage_id;
	
	private string _Firstname;
	
	private string _Lastname;
	
	private string _Phone_number;
	
	private string _Fax;
	
	private string _Email;
	
	private System.Nullable<bool> _Primary_contact;
	
	private string _Bio;
	
	private System.Nullable<decimal> _Rating;
	
	private string _Photo_filename;
	
	private System.Data.Linq.Binary _Picture;
	
	public RealEstateAgents()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agent_id", DbType="Int NOT NULL")]
	public int Agent_id
	{
		get
		{
			return this._Agent_id;
		}
		set
		{
			if ((this._Agent_id != value))
			{
				this._Agent_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brokerage_id", DbType="Int")]
	public System.Nullable<int> Brokerage_id
	{
		get
		{
			return this._Brokerage_id;
		}
		set
		{
			if ((this._Brokerage_id != value))
			{
				this._Brokerage_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="NVarChar(50)")]
	public string Firstname
	{
		get
		{
			return this._Firstname;
		}
		set
		{
			if ((this._Firstname != value))
			{
				this._Firstname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lastname", DbType="NVarChar(50)")]
	public string Lastname
	{
		get
		{
			return this._Lastname;
		}
		set
		{
			if ((this._Lastname != value))
			{
				this._Lastname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone_number", DbType="NVarChar(15)")]
	public string Phone_number
	{
		get
		{
			return this._Phone_number;
		}
		set
		{
			if ((this._Phone_number != value))
			{
				this._Phone_number = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(15)")]
	public string Fax
	{
		get
		{
			return this._Fax;
		}
		set
		{
			if ((this._Fax != value))
			{
				this._Fax = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this._Email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_contact", DbType="Bit")]
	public System.Nullable<bool> Primary_contact
	{
		get
		{
			return this._Primary_contact;
		}
		set
		{
			if ((this._Primary_contact != value))
			{
				this._Primary_contact = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bio", DbType="NVarChar(1024)")]
	public string Bio
	{
		get
		{
			return this._Bio;
		}
		set
		{
			if ((this._Bio != value))
			{
				this._Bio = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Decimal(2,1)")]
	public System.Nullable<decimal> Rating
	{
		get
		{
			return this._Rating;
		}
		set
		{
			if ((this._Rating != value))
			{
				this._Rating = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo_filename", DbType="NVarChar(50)")]
	public string Photo_filename
	{
		get
		{
			return this._Photo_filename;
		}
		set
		{
			if ((this._Photo_filename != value))
			{
				this._Photo_filename = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="Image", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary Picture
	{
		get
		{
			return this._Picture;
		}
		set
		{
			if ((this._Picture != value))
			{
				this._Picture = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class RealEstateData
{
	
	private System.Nullable<double> _Agent_id;
	
	private string _Firstname;
	
	private string _Lastname;
	
	private string _Photo_filename;
	
	private System.Nullable<System.DateTime> _Date;
	
	private System.Nullable<double> _Amount;
	
	private System.Nullable<double> _Realtor_comission_amount;
	
	private System.Nullable<double> _Tax_amount;
	
	public RealEstateData()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="agent_id", Storage="_Agent_id", DbType="Float")]
	public System.Nullable<double> Agent_id
	{
		get
		{
			return this._Agent_id;
		}
		set
		{
			if ((this._Agent_id != value))
			{
				this._Agent_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="NVarChar(255)")]
	public string Firstname
	{
		get
		{
			return this._Firstname;
		}
		set
		{
			if ((this._Firstname != value))
			{
				this._Firstname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lastname", DbType="NVarChar(255)")]
	public string Lastname
	{
		get
		{
			return this._Lastname;
		}
		set
		{
			if ((this._Lastname != value))
			{
				this._Lastname = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo_filename", DbType="NVarChar(255)")]
	public string Photo_filename
	{
		get
		{
			return this._Photo_filename;
		}
		set
		{
			if ((this._Photo_filename != value))
			{
				this._Photo_filename = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="date", Storage="_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this._Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="amount", Storage="_Amount", DbType="Float")]
	public System.Nullable<double> Amount
	{
		get
		{
			return this._Amount;
		}
		set
		{
			if ((this._Amount != value))
			{
				this._Amount = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="realtor_comission_amount", Storage="_Realtor_comission_amount", DbType="Float")]
	public System.Nullable<double> Realtor_comission_amount
	{
		get
		{
			return this._Realtor_comission_amount;
		}
		set
		{
			if ((this._Realtor_comission_amount != value))
			{
				this._Realtor_comission_amount = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="tax_amount", Storage="_Tax_amount", DbType="Float")]
	public System.Nullable<double> Tax_amount
	{
		get
		{
			return this._Tax_amount;
		}
		set
		{
			if ((this._Tax_amount != value))
			{
				this._Tax_amount = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class RealEstateSales
{
	
	private System.DateTime _Date;
	
	private decimal _Amount;
	
	private System.Nullable<decimal> _Realtor_comission_amount;
	
	private System.Nullable<decimal> _Tax_amount;
	
	private int _Property_id;
	
	private System.Nullable<int> _Agent_id;
	
	public RealEstateSales()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="date", Storage="_Date", DbType="DateTime NOT NULL")]
	public System.DateTime Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this._Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="amount", Storage="_Amount", DbType="Decimal(18,2) NOT NULL")]
	public decimal Amount
	{
		get
		{
			return this._Amount;
		}
		set
		{
			if ((this._Amount != value))
			{
				this._Amount = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="realtor_comission_amount", Storage="_Realtor_comission_amount", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> Realtor_comission_amount
	{
		get
		{
			return this._Realtor_comission_amount;
		}
		set
		{
			if ((this._Realtor_comission_amount != value))
			{
				this._Realtor_comission_amount = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="tax_amount", Storage="_Tax_amount", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> Tax_amount
	{
		get
		{
			return this._Tax_amount;
		}
		set
		{
			if ((this._Tax_amount != value))
			{
				this._Tax_amount = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="property_id", Storage="_Property_id", DbType="Int NOT NULL")]
	public int Property_id
	{
		get
		{
			return this._Property_id;
		}
		set
		{
			if ((this._Property_id != value))
			{
				this._Property_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="agent_id", Storage="_Agent_id", DbType="Int")]
	public System.Nullable<int> Agent_id
	{
		get
		{
			return this._Agent_id;
		}
		set
		{
			if ((this._Agent_id != value))
			{
				this._Agent_id = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class SouthAmericaPopulation
{
	
	private string _Country;
	
	private System.Nullable<double> _Population;
	
	public SouthAmericaPopulation()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(20)")]
	public string Country
	{
		get
		{
			return this._Country;
		}
		set
		{
			if ((this._Country != value))
			{
				this._Country = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Population", DbType="Float")]
	public System.Nullable<double> Population
	{
		get
		{
			return this._Population;
		}
		set
		{
			if ((this._Population != value))
			{
				this._Population = value;
			}
		}
	}
}
#pragma warning restore 1591